// Configuration for all lembaga desa modules
// Each config drives a generic LembagaModule component

export interface LembagaConfig {
  slug: string;
  nama: string;
  deskripsi?: string;
  jabatanLabel: string;
  jabatanOptions: Array<{ value: string; label: string }>;
  jabatanType: 'select' | 'text';
  defaultJabatan: string;
  showPekerjaan: boolean;
  anggotaLabel: string;
  showSkFields: boolean;
  // API
  apiUrl: string;
  reorderUrl: string;
  // Visual (card gradients + badge colors)
  gradientFrom: string;
  gradientTo: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  // Tab
  tabValue: string;
  icon: string;
  listTitle: string;
  emptyTitle: string;
  dialogTitle: string;
  dialogEditTitle: string;
}

export const lembagaConfigs: LembagaConfig[] = [
  {
    slug: 'bpd',
    nama: 'BPD',
    deskripsi: 'Badan Permusyawaratan Desa',
    jabatanLabel: 'Jabatan dalam BPD',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: false,
    apiUrl: '/api/lembaga-desa/bpd',
    reorderUrl: '/api/lembaga-desa/bpd/reorder',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-700',
    badgeBorder: 'border-blue-200',
    tabValue: 'bpd',
    icon: 'Building2',
    listTitle: 'Daftar Anggota BPD',
    emptyTitle: 'Belum ada data anggota BPD',
    dialogTitle: 'Tambah Anggota BPD',
    dialogEditTitle: 'Edit Anggota BPD',
  },
  {
    slug: 'lpm',
    nama: 'LPM',
    deskripsi: 'Lembaga Pemberdayaan Masyarakat',
    jabatanLabel: 'Jabatan dalam LPM',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Seksi Pemberdayaan Masyarakat', label: 'Seksi Pemberdayaan Masyarakat' },
      { value: 'Seksi Pengembangan Usaha', label: 'Seksi Pengembangan Usaha' },
      { value: 'Seksi Kesejahteraan Sosial', label: 'Seksi Kesejahteraan Sosial' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: false,
    apiUrl: '/api/lembaga-desa/lpm',
    reorderUrl: '/api/lembaga-desa/lpm/reorder',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-700',
    badgeBorder: 'border-amber-200',
    tabValue: 'lpm',
    icon: 'Users',
    listTitle: 'Daftar Anggota LPM',
    emptyTitle: 'Belum ada data anggota LPM',
    dialogTitle: 'Tambah Anggota LPM',
    dialogEditTitle: 'Edit Anggota LPM',
  },
  {
    slug: 'mui',
    nama: 'MUI',
    deskripsi: 'Majelis Ulama Indonesia',
    jabatanLabel: 'Jabatan dalam MUI',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: false,
    apiUrl: '/api/lembaga-desa/mui',
    reorderUrl: '/api/lembaga-desa/mui/reorder',
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    badgeBg: 'bg-green-50',
    badgeText: 'text-green-700',
    badgeBorder: 'border-green-200',
    tabValue: 'mui',
    icon: 'Building2',
    listTitle: 'Daftar Anggota MUI',
    emptyTitle: 'Belum ada data anggota MUI',
    dialogTitle: 'Tambah Anggota MUI',
    dialogEditTitle: 'Edit Anggota MUI',
  },
  {
    slug: 'karangTaruna',
    nama: 'Karang Taruna',
    deskripsi: 'Organisasi Kepemudaan',
    jabatanLabel: 'Jabatan dalam Karang Taruna',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Sie Pendidikan', label: 'Sie Pendidikan' },
      { value: 'Sie Kesenian', label: 'Sie Kesenian' },
      { value: 'Sie Olahraga', label: 'Sie Olahraga' },
      { value: 'Sie Keterampilan', label: 'Sie Keterampilan' },
      { value: 'Sie Sosial', label: 'Sie Sosial' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: false,
    apiUrl: '/api/lembaga-desa/karang-taruna',
    reorderUrl: '/api/lembaga-desa/karang-taruna/reorder',
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-700',
    badgeBorder: 'border-purple-200',
    tabValue: 'karangTaruna',
    icon: 'Users',
    listTitle: 'Daftar Anggota Karang Taruna',
    emptyTitle: 'Belum ada data anggota Karang Taruna',
    dialogTitle: 'Tambah Anggota Karang Taruna',
    dialogEditTitle: 'Edit Anggota Karang Taruna',
  },
  {
    slug: 'pkk',
    nama: 'PKK',
    jabatanLabel: 'Jabatan dalam PKK',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Pokja I', label: 'Pokja I - Pendidikan & Pelatihan' },
      { value: 'Pokja II', label: 'Pokja II - Usaha Peningkatan Pendapatan Keluarga' },
      { value: 'Pokja III', label: 'Pokja III - Sandang & Pangan' },
      { value: 'Pokja IV', label: 'Pokja IV - Perumahan & Tata Laksana Rumah Tangga' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/pkk',
    reorderUrl: '/api/lembaga-desa/pkk/reorder',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-pink-600',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-700',
    badgeBorder: 'border-rose-200',
    tabValue: 'pkk',
    icon: 'Heart',
    listTitle: 'Daftar Anggota PKK',
    emptyTitle: 'Belum ada data anggota PKK',
    dialogTitle: 'Tambah Anggota PKK',
    dialogEditTitle: 'Edit Anggota PKK',
  },
  {
    slug: 'ketuaRW',
    nama: 'Ketua RW',
    jabatanLabel: 'Jabatan dalam RW',
    jabatanOptions: [
      { value: 'Ketua RW', label: 'Ketua RW' },
      { value: 'Wakil Ketua RW', label: 'Wakil Ketua RW' },
      { value: 'Sekretaris RW', label: 'Sekretaris RW' },
      { value: 'Bendahara RW', label: 'Bendahara RW' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/ketua-rw',
    reorderUrl: '/api/lembaga-desa/ketua-rw/reorder',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-700',
    badgeBorder: 'border-amber-200',
    tabValue: 'ketuaRW',
    icon: 'Users',
    listTitle: 'Daftar Ketua RW',
    emptyTitle: 'Belum ada data Ketua RW',
    dialogTitle: 'Tambah Anggota Ketua RW',
    dialogEditTitle: 'Edit Anggota Ketua RW',
  },
  {
    slug: 'ketuaRT',
    nama: 'Ketua RT',
    jabatanLabel: 'Jabatan dalam RT',
    jabatanOptions: [],
    jabatanType: 'text',
    defaultJabatan: '',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/ketua-rt',
    reorderUrl: '/api/lembaga-desa/ketua-rt/reorder',
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-600',
    badgeBg: 'bg-violet-50',
    badgeText: 'text-violet-700',
    badgeBorder: 'border-violet-200',
    tabValue: 'ketuaRT',
    icon: 'Users',
    listTitle: 'Daftar Ketua RT',
    emptyTitle: 'Belum ada data Ketua RT',
    dialogTitle: 'Tambah Anggota Ketua RT',
    dialogEditTitle: 'Edit Anggota Ketua RT',
  },
  {
    slug: 'linmas',
    nama: 'Linmas',
    deskripsi: 'Perlindungan Masyarakat',
    jabatanLabel: 'Jabatan dalam Linmas',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Koordinator', label: 'Koordinator' },
      { value: 'Komandan Regu', label: 'Komandan Regu' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Anggota',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/linmas',
    reorderUrl: '/api/lembaga-desa/linmas/reorder',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-red-600',
    badgeBg: 'bg-rose-50',
    badgeText: 'text-rose-700',
    badgeBorder: 'border-rose-200',
    tabValue: 'linmas',
    icon: 'Shield',
    listTitle: 'Daftar Anggota Linmas',
    emptyTitle: 'Belum ada data Linmas',
    dialogTitle: 'Tambah Anggota Linmas',
    dialogEditTitle: 'Edit Anggota Linmas',
  },
  {
    slug: 'bumdes',
    nama: 'Bumdes',
    deskripsi: 'Badan Usaha Milik Desa',
    jabatanLabel: 'Jabatan dalam Bumdes',
    jabatanOptions: [
      { value: 'Direktur', label: 'Direktur' },
      { value: 'Wakil Direktur', label: 'Wakil Direktur' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Manajer', label: 'Manajer' },
      { value: 'Kepala Unit', label: 'Kepala Unit' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Pengurus',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/bumdes',
    reorderUrl: '/api/lembaga-desa/bumdes/reorder',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-green-600',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-700',
    badgeBorder: 'border-emerald-200',
    tabValue: 'bumdes',
    icon: 'Store',
    listTitle: 'Daftar Pengurus Bumdes',
    emptyTitle: 'Belum ada data Bumdes',
    dialogTitle: 'Tambah Pengurus Bumdes',
    dialogEditTitle: 'Edit Pengurus Bumdes',
  },
  {
    slug: 'koperasi',
    nama: 'Koperasi',
    jabatanLabel: 'Jabatan dalam Koperasi',
    jabatanOptions: [
      { value: 'Ketua', label: 'Ketua' },
      { value: 'Wakil Ketua', label: 'Wakil Ketua' },
      { value: 'Sekretaris', label: 'Sekretaris' },
      { value: 'Bendahara', label: 'Bendahara' },
      { value: 'Pengawas', label: 'Pengawas' },
      { value: 'Manajer Unit', label: 'Manajer Unit' },
      { value: 'Anggota', label: 'Anggota' },
    ],
    jabatanType: 'select',
    defaultJabatan: 'Anggota',
    showPekerjaan: true,
    anggotaLabel: 'Pengurus',
    showSkFields: true,
    apiUrl: '/api/lembaga-desa/koperasi',
    reorderUrl: '/api/lembaga-desa/koperasi/reorder',
    gradientFrom: 'from-red-500',
    gradientTo: 'to-rose-600',
    badgeBg: 'bg-red-50',
    badgeText: 'text-red-700',
    badgeBorder: 'border-red-200',
    tabValue: 'koperasi',
    icon: 'CircleDollarSign',
    listTitle: 'Daftar Pengurus Koperasi',
    emptyTitle: 'Belum ada data Koperasi',
    dialogTitle: 'Tambah Pengurus Koperasi',
    dialogEditTitle: 'Edit Pengurus Koperasi',
  },
];

// Perangkat Desa jabatan options (used in PerangkatDesa-specific form)
export const jabatanPerangkatOptions = [
  { value: 'KEPALA_DESA', label: 'Kepala Desa' },
  { value: 'SEKRETARIS_DESA', label: 'Sekretaris Desa' },
  { value: 'KAUR_TATA_USAHA', label: 'Kaur Tata Usaha' },
  { value: 'KAUR_KEUANGAN', label: 'Kaur Keuangan' },
  { value: 'KAUR_PERENCANAAN', label: 'Kaur Perencanaan' },
  { value: 'KASI_PEMERINTAHAN', label: 'Kasi Pemerintahan' },
  { value: 'KASI_KESRA', label: 'Kasi Kesejahteraan' },
  { value: 'KASI_PELAYANAN', label: 'Kasi Pelayanan' },
  { value: 'KEPALA_DUSUN', label: 'Kepala Dusun' },
  { value: 'LAINNYA', label: 'Lainnya' },
];
